version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    stdin_open: true
    tty: true
    depends_on:
      - server
