version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - rabbitmq
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
