# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialization_test_object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fserialization_test_object.proto\"\xdc\x01\n\x17SerializationTestObject\x12\x18\n\x10non_empty_string\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x05\x12<\n\ndictionary\x18\x03 \x03(\x0b\x32(.SerializationTestObject.DictionaryEntry\x12\x0f\n\x07integer\x18\x04 \x01(\x05\x12\x16\n\x0e\x66loating_point\x18\x05 \x01(\x01\x1a\x31\n\x0f\x44ictionaryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serialization_test_object_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERIALIZATIONTESTOBJECT_DICTIONARYENTRY._options = None
  _SERIALIZATIONTESTOBJECT_DICTIONARYENTRY._serialized_options = b'8\001'
  _SERIALIZATIONTESTOBJECT._serialized_start=36
  _SERIALIZATIONTESTOBJECT._serialized_end=256
  _SERIALIZATIONTESTOBJECT_DICTIONARYENTRY._serialized_start=207
  _SERIALIZATIONTESTOBJECT_DICTIONARYENTRY._serialized_end=256
# @@protoc_insertion_point(module_scope)
